//
// Basic colorwheel base color picker using HTML5/Javascript
//
const char* html_header =
"<head>"
"<style>"
"body {"
"    overflow:hidden;"
"    background:black;"
"}"
"</style>"
"</head>\n"
"<body>"
"<canvas id='wheelCanvas' onclick='getColor(event)'>"
"</canvas>"
"<script type='text/javascript'>"
"	var canvas = document.getElementById('wheelCanvas');\n"
"	var context = canvas.getContext('2d');\n"
"	var imageObj = new Image();\n"
"	imageObj.crossOrigin = 'anonymous';\n"
"	var dimension;\n"
"	if(window.innerHeight<window.innerWidth){\n"
"		dimension=window.innerHeight;\n"
"	} else {\n"
"      	dimension=window.innerWidth;\n"
"	}\n"
"	imageObj.onload = function() {"
"		context.drawImage(imageObj,0,0,600,600,0,0,0.98*dimension,0.98*dimension);"
"	};"
"	imageObj.src = 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/RGB_color_wheel_360.svg/600px-RGB_color_wheel_360.svg.png';"
"	canvas.height=window.innerHeight;"
"	canvas.width=window.innerWidth;"
"function getColor(event) {"
"	var canvas = document.getElementById('wheelCanvas');"
"	var rect = canvas.getBoundingClientRect();"
"    var pixelData = canvas.getContext('2d').getImageData(event.offsetX, event.offsetY, 1, 1).data;"
"    var form = document.createElement('form');"
"    form.action='out';"
"    var nr = document.createElement('input');"
"    nr.name='R';"
"    nr.value=pixelData[0].toString();"
"    form.appendChild(nr);"
"    var ng = document.createElement('input');"
"    ng.name='G';"
"    ng.value=pixelData[1].toString();"
"    form.appendChild(ng);"
"    var nb = document.createElement('input');"
"    nb.name='B';"
"    nb.value=pixelData[2].toString();"
"    form.appendChild(nb);"
"		var size = Math.min(canvas.width,canvas.height);"
"		var myX = (event.offsetX-0.5*size)/size;"
"		var myY = (event.offsetY-0.5*size)/size;"
"		var radius = Math.sqrt(Math.pow(myX,2) + Math.pow(myY,2));"
"		var intensity = 100*(radius-0.16)/(0.5-0.16);"
"		intensity = Math.max(0,intensity);"
"		intensity = Math.min(100,intensity);"
"		var nb = document.createElement('input');"
"		nb.name='X';"
"		nb.value=myX.toFixed(2).toString();"
"		form.appendChild(nb);"
"		var nb = document.createElement('input');"
"		nb.name='Y';"
"		nb.value=myY.toFixed(2).toString();"
"		form.appendChild(nb);"
"		var nb = document.createElement('input');"
"		nb.name='intensity';"
"		nb.value=intensity.toFixed(0).toString();"
"		form.appendChild(nb);"
"    form.style.display='none';"
"    document.body.appendChild(form);"
"    form.submit();"
"}"
"</script>"

"</body>";
